### PR TITLE
refactor: Turn on noUnusedLocals, fix errors.

### LINKED ISSUE #116: audit eslint / prettier configs - not catching uninitialized class members
Check and make sure that the eslint/prettier configs are up to date with what we've been using internally.

In particular - I noticed that if I was writing a class that had some private readonly member variables, and those variables were not initialized in the constructor, I didn't get a build/lint error.  In our CDK repos I believe we would catch that at compile time.

### PR DESCRIPTION
**Pull request by schwern**
For some reason, the linter was configured to allow unused local properties. The check is off on nearly all our Typescript repos. There doesn't seem to be a reason not to turn the check on.

Closes #116

### CODE REVIEW

File: src/simple-cache-client.ts [hunk 1]
```diff
@@ -54,14 +54,12 @@ export class SimpleCacheClient {
...
   private nextDataClientIndex: number;
   private readonly controlClient: ControlClient;
-  private readonly logger: Logger;
 
   /**
    * Creates an instance of SimpleCacheClient.
    */
   constructor(props: SimpleCacheClientProps) {
     initializeMomentoLogging(props.configuration.getLoggerOptions());
-    this.logger = getLogger(this);
```
Comment (cprice404) [inline src/simple-cache-client.ts:64]: Instead of removing this can you just add a debug log message to the constructor or something?  We will be coming back in here and adding logging at some point and I want to make sure it's really easy for devs to figure out how to do it.

**Review by cprice404 — COMMENTED** [review]
thanks for doing this, I agree with the spirit of it.  just a few questions about the couple of impacted variables.

File: src/errors/errors.ts [hunk 2]
```diff
@@ -55,7 +55,6 @@ export abstract class SdkError extends Error {
   protected readonly _errorCode: MomentoErrorCode;
   protected readonly _messageWrapper: string;
   private readonly _transportDetails: MomentoErrorTransportDetails;
-  private readonly _stack: string | undefined;
```
[the remark this answers is not in the document]
Comment (schwern) [reply src/errors/errors.ts:58]: eslint and a search for `_stack` say we're not.

I know we discussed storing the stack in error messages, but we're not consistent about that.

File: src/simple-cache-client.ts (hunk 1 above)
Comment (schwern) [reply src/simple-cache-client.ts:64]: I went to do that, and there's very little to log in SimpleCacheClient. All the work is in CacheClient and ControlClient. I think this is at the wrong level.

**Review by cprice404 — APPROVED** [review]
